import { describe, expect, it, vi } from "vitest";
import { renderHook } from "@testing-library/react";
import { useAppShellSideEffectsController } from "./useAppShellSideEffectsController";

describe("useAppShellSideEffectsController", () => {
  it("returns nothing (side-effect-only surface)", () => {
    const { result } = renderHook(() =>
      useAppShellSideEffectsController({
        actions: {
          createNewFile: vi.fn(),
          exportHtml: vi.fn(),
          exportPdf: vi.fn(),
          openAgentWindow: vi.fn(),
          openFile: vi.fn(),
          openWorkspace: vi.fn(),
          openWorkspacePath: vi.fn(),
          requestWindowClose: vi.fn(),
          saveActiveTab: vi.fn(),
          saveActiveTabAs: vi.fn(),
          toggleReviewDesk: vi.fn(),
        },
        listener: {
          onOpenRecentFile: vi.fn(),
          recentFilesRef: { current: [] },
          recentFoldersRef: { current: [] },
          setEditorSettings: vi.fn(),
          setPreferencesDialogMode: vi.fn(),
          setPreviewVisible: vi.fn(),
          setThemePreference: vi.fn(),
        },
        activity: {
          onResumeAgentUiRefresh: vi.fn(),
          onSuspendAgentUiRefresh: vi.fn(),
          onToggleQuickOpen: vi.fn(),
        },
        agentSessionSync: {
          activeAgentSession: false,
          agentSession: null,
          agentUiSuspendedRef: { current: false },
          agentWorkbenchAvailable: false,
          onRefreshAgentSessionState: vi.fn(),
          onResetAgentOutput: vi.fn(),
          setAgentLaunchGate: vi.fn(),
          setAgentSession: vi.fn(),
          workspaceRootPath: null,
        },
        appShellSync: {
          activeDirty: false,
          activeTab: null,
          agentWorkbenchActive: false,
          agentWorkbenchConsent: false,
          discardingWindowCloseRef: { current: false },
          editorSettings: {
            wrapLines: true,
            showInvisibles: false,
            fontSize: 14,
            tabSize: 2,
            spellcheckEnabled: true,
            autoBackupEnabled: true,
            ambientIntensity: "subtle",
          },
          menuLanguage: "en",
          pendingDrafts: [],
          previewVisible: true,
          recentFiles: [],
          recentFolders: [],
          restoreComplete: false,
          selectedImage: null,
          tabs: [],
          themePreference: "light",
          workspaceRootPath: null,
        },
        workspaceRuntime: {
          activeTabPath: null,
          closeWorkspaceContextMenu: vi.fn(),
          insertMarkdownAtCursor: vi.fn(),
          openExternalFilePaths: vi.fn(),
          restoreComplete: false,
          setActiveTabId: vi.fn(),
          setGlobalError: vi.fn(),
          setPendingDrafts: vi.fn(),
          setRestoreComplete: vi.fn(),
          setStatus: vi.fn(),
          setTabs: vi.fn(),
          setWorkspaceRootPath: vi.fn(),
          setWorkspaceTree: vi.fn(),
          workspaceContextMenuOpen: false,
          workspaceRootPath: null,
        },
        keyboardFocus: {
          activeAgentSession: false,
          activeTabId: null,
          agentUiSuspendedRef: { current: false },
          allowWindowCloseRef: { current: false },
          appCloseCancelButtonRef: { current: null },
          appCloseDialogRef: { current: null },
          closeTabCancelButtonRef: { current: null },
          closeTabDialogRef: { current: null },
          commandPaletteVisible: false,
          dirtyTabCount: 0,
          editorPaneRef: { current: null },
          findInputRef: { current: null },
          findVisible: false,
          globalSearchVisible: false,
          modalOpen: false,
          onApplyMarkdownFormat: vi.fn(),
          onCancelAppClose: vi.fn(),
          onCancelTabClose: vi.fn(),
          onCheckTabForExternalChange: vi.fn(),
          onCloseCommandPalette: vi.fn(),
          onCloseFindAndFocusEditor: vi.fn(),
          onCloseGlobalSearch: vi.fn(),
          onClosePreferences: vi.fn(),
          onCloseSelectedImagePreview: vi.fn(),
          onCreateNewFile: vi.fn(),
          onFocusAdjacentTab: vi.fn(),
          onFocusEditorSoon: vi.fn(),
          onNeedsWindowCloseConfirmation: vi.fn(),
          onOpenCommandPalette: vi.fn(),
          onOpenFile: vi.fn(),
          onOpenGlobalSearch: vi.fn(),
          onOpenWorkspace: vi.fn(),
          onRequestCloseTab: vi.fn(),
          onRequestWindowClose: vi.fn(),
          onSaveActiveTab: vi.fn(),
          onSaveActiveTabAs: vi.fn(),
          onToggleReviewDesk: vi.fn(),
          pendingAppClose: false,
          pendingCloseTabOpen: false,
          preferencesCloseButtonRef: { current: null },
          preferencesDialogRef: { current: null },
          preferencesOpen: false,
          selectedImageOpen: false,
          setEditorSettings: vi.fn(),
          setFindVisible: vi.fn(),
          setPreferencesDialogMode: vi.fn(),
          setPreviewVisible: vi.fn(),
          setStatus: vi.fn(),
        },
      }),
    );

    // Side-effect-only surface: returns nothing.
    expect(result.current).toBeUndefined();
  });
});
