// xterm imports moved to AgentTerminalView component
import { useAppPreferences } from "./hooks/useAppPreferences";
import { useRecentEntries } from "./hooks/useRecentEntries";
import { useAppMenuIntegration } from "./hooks/useAppMenuIntegration";
import { useWindowDialogActions } from "./hooks/useWindowDialogActions";
import { usePastedImageAction } from "./hooks/usePastedImageAction";
import { useAgentWorkbenchPreferenceActions } from "./hooks/useAgentWorkbenchPreferenceActions";
import { useAgentTerminalActions } from "./hooks/useAgentTerminalActions";
import { useAgentWorkbenchSessionActions } from "./hooks/useAgentWorkbenchSessionActions";
import { useDocumentSafetyActions } from "./hooks/useDocumentSafetyActions";
import { useEditorTabState } from "./hooks/useEditorTabState";
import { useSidePaneController } from "./hooks/useSidePaneController";
import { useAppRuntimeEffects } from "./hooks/useAppRuntimeEffects";
import { useAgentOutputBuffer } from "./hooks/useAgentOutputBuffer";
import { useAgentUiRefreshGate } from "./hooks/useAgentUiRefreshGate";
import { useWorkspaceFileOpening } from "./hooks/useWorkspaceFileOpening";
import { useCompareController } from "./hooks/useCompareController";
import { useDocumentIoController } from "./hooks/useDocumentIoController";
import { useGoToLine } from "./hooks/useGoToLine";
import { useImagePreview } from "./hooks/useImagePreview";
import { useWorkspaceContextMenu } from "./hooks/useWorkspaceContextMenu";
import { useQuickOpenState } from "./hooks/useQuickOpenState";
import { useEditorCommands } from "./hooks/useEditorCommands";
import { useTabBarController } from "./hooks/useTabBarController";
import { useLocalizedAppCopy } from "./hooks/useLocalizedAppCopy";
import { useAppDialogRefs } from "./hooks/useAppDialogRefs";
import { useFindReplaceController } from "./hooks/useFindReplaceController";
import { useAppEditorRefs } from "./hooks/useAppEditorRefs";
import { useCompareState } from "./hooks/useCompareState";
import { useWorkspaceShellState } from "./hooks/useWorkspaceShellState";
import { useEditorSelectionState } from "./hooks/useEditorSelectionState";
import { useAppDialogState } from "./hooks/useAppDialogState";
import { useAppViewState } from "./hooks/useAppViewState";
import { useDraftRecoveryState } from "./hooks/useDraftRecoveryState";
import { useAppFeedbackState } from "./hooks/useAppFeedbackState";
import { useEditorTabsState } from "./hooks/useEditorTabsState";
import { useAgentWorkbenchRuntimeState } from "./hooks/useAgentWorkbenchRuntimeState";
import { useActiveDocumentIdentity } from "./hooks/useActiveDocumentIdentity";
import { useActiveDocumentSurface } from "./hooks/useActiveDocumentSurface";
import { AppShell, type AppShellProps } from "./components/AppShell";

export default function App() {
  const {
    activeAgentSession,
    agentLaunchGate,
    agentSession,
    agentStopPending,
    agentTerminalSize,
    appRestartPending,
    setAgentLaunchGate,
    setAgentSession,
    setAgentStopPending,
    setAgentTerminalSize,
    setAppRestartPending,
  } = useAgentWorkbenchRuntimeState();
  const {
    pendingAppClose,
    pendingCloseTabId,
    preferencesDialogMode,
    setPendingAppClose,
    setPendingCloseTabId,
    setPreferencesDialogMode,
  } = useAppDialogState();
  const { rightPaneMode, setRightPaneMode, setZenMode, zenMode, reviewSurface } =
    useAppViewState();
  const { pendingDrafts, setPendingDrafts } = useDraftRecoveryState();
  const { globalError, setGlobalError, setStatus, status } =
    useAppFeedbackState();
  const { activeTabId, setActiveTabId, setTabs, tabs } = useEditorTabsState();
  const { selectionInfo, setSelectionInfo } = useEditorSelectionState();
  const {
    compareAnchor,
    compareTarget,
    compareView,
    getCompareCaseByKey,
    setCompareAnchor,
    setCompareCaseEntry,
    setCompareTarget,
    setCompareView,
  } = useCompareState();
  const {
    restoreComplete,
    setRestoreComplete,
    setWorkspaceRootPath,
    setWorkspaceTree,
    workspaceRootPath,
    workspaceTree,
  } = useWorkspaceShellState();
  const {
    agentWorkbenchActive,
    agentWorkbenchConsent,
    agentWorkbenchPreference,
    agentWorkbenchProvider,
    editorSettings,
    editorTheme,
    menuLanguage,
    previewVisible,
    resolvedTheme,
    setAgentWorkbenchConsent,
    setAgentWorkbenchPreference,
    setAgentWorkbenchProvider,
    setEditorSettings,
    setMenuLanguage,
    setPreviewVisible,
    setThemePreference,
    themePreference,
  } = useAppPreferences();
  const {
    editorPaneRef,
    findInputRef,
    previewPaneRef,
    tabsRef,
  } = useAppEditorRefs(tabs);
  const {
    recentFiles,
    recentFilesRef,
    recentFolders,
    recentFoldersRef,
    rememberRecentFile,
    rememberRecentFolder,
  } = useRecentEntries();
  const {
    agentUiSuspendedRef,
    resumeAgentUiRefresh,
    suspendAgentUiRefresh,
  } = useAgentUiRefreshGate();

  const {
    activeConflict,
    activeContents,
    activeDirty,
    activeDraft,
    activeError,
    activeSaveError,
    activeTab,
    dirtyTabCount,
    dirtyTabs,
    pendingCloseTab,
  } = useEditorTabState({
    activeTabId,
    globalError,
    pendingCloseTabId,
    pendingDrafts,
    tabs,
  });
  const {
    clearImagePreview,
    closeSelectedImagePreview,
    imageReturnTabId,
    openImagePreview,
    selectedImage,
  } = useImagePreview({
    activeTabId,
    onError: setGlobalError,
    onStatus: setStatus,
    setActiveTabId,
    setCompareView,
    tabs,
    workspaceRootPath,
  });
  const {
    activeTabPath,
    documentKey,
    hasActiveDocument,
    selectedImageOpen,
  } =
    useActiveDocumentIdentity({
      activeTab,
      selectedImage,
    });
  const {
    closeWorkspaceContextMenu,
    openWorkspaceContextMenu,
    workspaceContextMenu,
  } = useWorkspaceContextMenu();
  const {
    closeQuickOpen,
    quickOpenVisible,
    toggleQuickOpen,
  } = useQuickOpenState();
  const {
    applyActiveMarkdownFormat,
    convertActiveLineEnding,
    handleEditorChange,
    insertMarkdownAtCursor,
    insertTable,
    jumpToHeading,
  } = useEditorCommands({
    activeTab,
    activeTabId,
    editorPaneRef,
    setStatus,
    setTabs,
  });
  const {
    agentWorkbenchCopy,
    agentWorkbenchModeBadge,
    agentWorkbenchRestartRequired,
    editorChromeCopy,
    preferencesCopy,
    recoveryCopy,
    safeEditorCopy,
    sidePaneCopy,
  } = useLocalizedAppCopy({
    agentWorkbenchActive,
    agentWorkbenchPreference,
    menuLanguage,
  });
  const {
    agentPaneVisible,
    agentWorkbenchAvailable,
    editorPreviewGridRef,
    editorPreviewGridStyle,
    handlePreviewResizeKeyDown,
    handlePreviewResizePointerDown,
    handlePreviewResizePointerMove,
    hasWorkspaceSelection,
    previewColumnPercent,
    sidePaneMode,
    sidePaneVisible,
    toggleAgentPane,
    toggleDiffPane,
    toggleOutlinePane,
    togglePreviewPane,
  } = useSidePaneController({
    activeTab,
    agentWorkbenchActive,
    agentWorkbenchConsent,
    compareView,
    previewVisible,
    rightPaneMode,
    selectedImage,
    setPreviewVisible,
    setRightPaneMode,
  });
  const {
    activeDocumentLineCount,
    activeStatusDetail,
    currentMarkdownHeading,
    documentHeadings,
    documentOutline,
    scrollHudContext,
    scrollHudLine,
    scrollHudVisible,
    syncEditorScroll,
    syncPreviewScroll,
  } = useActiveDocumentSurface({
    activeContents,
    activeDirty,
    activeTab,
    compareView,
    editorPaneRef,
    getCompareCaseByKey,
    hasActiveDocument,
    menuLanguage,
    noFileOpenText: safeEditorCopy.noFileOpen,
    previewPaneRef,
    selectedImage,
    selectionInfo,
    sidePaneMode,
  });
  const {
    activeMatchIndex,
    closeFindAndFocusEditor,
    findMatchCount,
    findMatches,
    findQuery,
    findVisible,
    handleFindKeyDown,
    handleReplaceKeyDown,
    invalidRegex,
    replaceAll,
    replaceOne,
    replaceQuery,
    searchOptions,
    setFindQuery,
    setFindVisible,
    setReplaceQuery,
    setSearchOptions,
    showNextMatch,
    showPreviousMatch,
  } = useFindReplaceController({
    documentKey,
    editorPaneRef,
    setStatus,
    source: activeContents,
  });
  const {
    goToLine,
    goToLineValue,
    handleGoToLineKeyDown,
    setGoToLineValue,
  } = useGoToLine({
    editorPaneRef,
    onStatus: setStatus,
  });
  const { agentOutput, applyAgentOutput, resetAgentOutput } =
    useAgentOutputBuffer();
  const {
    createNewFile,
    loadWorkspaceDirectory,
    openExternalFilePaths,
    openFile,
    openFilePath,
    openWorkspace,
    openWorkspacePath,
    openPreviewMarkdownLink,
    openWorkspaceFile,
    refreshWorkspaceTree,
  } = useWorkspaceFileOpening({
    activeTab,
    clearImagePreview,
    menuLanguage,
    openImagePreview,
    rememberRecentFile,
    rememberRecentFolder,
    setActiveTabId,
    setCompareAnchor,
    setCompareTarget,
    setCompareView,
    setGlobalError,
    setPendingDrafts,
    setStatus,
    setTabs,
    setWorkspaceRootPath,
    setWorkspaceTree,
    tabs,
    workspaceRootPath,
  });
  const {
    allowWindowCloseRef,
    appCloseCancelButtonRef,
    appCloseDialogRef,
    closeTabCancelButtonRef,
    closeTabDialogRef,
    discardingWindowCloseRef,
    modalOpen,
    pendingCloseTabOpen,
    preferencesCloseButtonRef,
    preferencesDialogRef,
    preferencesOpen,
  } = useAppDialogRefs({
    pendingAppClose,
    pendingCloseTab,
    preferencesDialogMode,
  });
  const {
    cancelPendingAppClose,
    cancelPendingTabClose,
    closePreferencesFromKeyboard,
    focusEditorSoon,
    requestAppCloseConfirmation,
    requestWindowClose,
  } = useWindowDialogActions({
    editorPaneRef,
    setGlobalError,
    setPendingAppClose,
    setPendingCloseTabId,
    setPreferencesDialogMode,
    setStatus,
  });
  const {
    draggingTabId,
    dragOverTabId,
    finishTabPointerDrag,
    focusAdjacentTab,
    handleTabPointerDown,
    handleTabPointerMove,
    selectTabFromBar,
    shouldSuppressTabClick,
  } = useTabBarController({
    activeTabId,
    clearImagePreview,
    focusEditorSoon,
    imageReturnTabId,
    setActiveTabId,
    setTabs,
    setStatus,
    tabs,
  });

  const {
    clearCompareSource,
    clearCompareTarget,
    closeCompareView,
    compareWorkspaceFiles,
    copyWorkspaceFullPath,
    requestReviewDraftAgainstDisk,
    requestReviewTabAgainstDisk,
    revealWorkspacePath,
    runSelectedFileCompare,
    selectWorkspaceCompareFile,
    setCompareSource,
    setCompareTargetFile,
  } = useCompareController({
    activeTab,
    closeWorkspaceContextMenu,
    compareAnchor,
    compareTarget,
    menuLanguage,
    setCompareAnchor,
    setCompareCaseEntry,
    setCompareTarget,
    setCompareView,
    setGlobalError,
    setRightPaneMode,
    setStatus,
  });

  const {
    exportHtml,
    exportPdf,
    saveActiveTab,
    saveActiveTabAs,
    saveTabById,
  } = useDocumentIoController({
    activeContents,
    activeTab,
    activeTabId,
    autoBackupEnabled: editorSettings.autoBackupEnabled,
    refreshWorkspaceTree,
    rememberRecentFile,
    setActiveTabId,
    setGlobalError,
    setStatus,
    setTabs,
    tabs,
    workspaceRootPath,
  });

  useAppMenuIntegration({
    actions: {
      createNewFile,
      exportHtml,
      exportPdf,
      openFile,
      openWorkspace,
      openWorkspacePath,
      requestWindowClose,
      saveActiveTab,
      saveActiveTabAs,
    },
    listener: {
      onOpenRecentFile: openFilePath,
      recentFilesRef,
      recentFoldersRef,
      setEditorSettings,
      setPreferencesDialogMode,
      setPreviewVisible,
      setThemePreference,
      setZenMode,
    },
  });

  const {
    checkTabForExternalChange,
    clearSaveError,
    closeTabNow,
    discardDraft,
    discardAllAndCloseWindow,
    keepEditingAfterConflict,
    reopenTabFromDisk,
    requestCloseTab,
    restoreDraft,
    saveAllAndCloseWindow,
    saveAndClosePendingTab,
  } = useDocumentSafetyActions({
    activeTabId,
    allowWindowCloseRef,
    dirtyTabs,
    discardingWindowCloseRef,
    focusEditorSoon,
    pendingCloseTabId,
    saveTabById,
    setActiveTabId,
    setGlobalError,
    setPendingAppClose,
    setPendingCloseTabId,
    setPendingDrafts,
    setStatus,
    setTabs,
    tabs,
    tabsRef,
  });

  const {
    restartAppForAgentMode,
    updateAgentWorkbenchConsent,
    updateAgentWorkbenchPreference,
    updateAgentWorkbenchProvider,
  } = useAgentWorkbenchPreferenceActions({
    activeAgentSession,
    agentWorkbenchActive,
    menuLanguage,
    setAgentLaunchGate,
    setAgentWorkbenchConsent,
    setAgentWorkbenchPreference,
    setAgentWorkbenchProvider,
    setAppRestartPending,
    setGlobalError,
    setStatus,
  });

  const {
    refreshAgentSessionState,
    requestAgentLaunchGateCheck,
    requestAgentSessionStop,
    sendWorkspacePathToAgent,
  } = useAgentWorkbenchSessionActions({
    agentSession,
    agentTerminalSize,
    agentWorkbenchActive,
    agentWorkbenchConsent,
    agentWorkbenchProvider,
    applyAgentOutput,
    closeWorkspaceContextMenu,
    menuLanguage,
    setAgentLaunchGate,
    setAgentSession,
    setAgentStopPending,
    setGlobalError,
    setStatus,
    workspaceRootPath,
  });

  const {
    handlePresetPrompt,
    handleSendSelectionToAgent,
    resizeAgentTerminal,
    sendAgentTerminalData,
  } = useAgentTerminalActions({
    agentSession,
    editorPaneRef,
    onRefreshAgentSessionState: refreshAgentSessionState,
    setAgentLaunchGate,
    setAgentSession,
    setAgentTerminalSize,
    setStatus,
  });

  const { handlePasteImage } = usePastedImageAction({
    activeTabPath,
    setStatus,
    workspaceRootPath,
  });

  useAppRuntimeEffects({
    activity: {
      onResumeAgentUiRefresh: resumeAgentUiRefresh,
      onSuspendAgentUiRefresh: suspendAgentUiRefresh,
      onToggleQuickOpen: toggleQuickOpen,
    },
    agentSessionSync: {
      activeAgentSession,
      agentSession,
      agentUiSuspendedRef,
      agentWorkbenchAvailable,
      onRefreshAgentSessionState: refreshAgentSessionState,
      onResetAgentOutput: resetAgentOutput,
      rightPaneMode,
      setAgentLaunchGate,
      setAgentSession,
      setRightPaneMode,
      workspaceRootPath,
    },
    appShellSync: {
      activeDirty,
      activeTab,
      discardingWindowCloseRef,
      editorSettings,
      menuLanguage,
      pendingDrafts,
      previewVisible,
      recentFiles,
      recentFolders,
      restoreComplete,
      selectedImage,
      tabs,
      themePreference,
      workspaceRootPath,
      zenMode,
    },
    workspaceRuntime: {
      activeTabPath,
      closeWorkspaceContextMenu,
      insertMarkdownAtCursor,
      openExternalFilePaths,
      restoreComplete,
      setActiveTabId,
      setGlobalError,
      setPendingDrafts,
      setRestoreComplete,
      setStatus,
      setTabs,
      setWorkspaceRootPath,
      setWorkspaceTree,
      workspaceContextMenuOpen: workspaceContextMenu !== null,
      workspaceRootPath,
    },
    keyboardFocus: {
      activeAgentSession,
      activeTabId,
      agentUiSuspendedRef,
      allowWindowCloseRef,
      appCloseCancelButtonRef,
      appCloseDialogRef,
      closeTabCancelButtonRef,
      closeTabDialogRef,
      dirtyTabCount,
      editorPaneRef,
      findInputRef,
      findVisible,
      modalOpen,
      onApplyMarkdownFormat: applyActiveMarkdownFormat,
      onCancelAppClose: cancelPendingAppClose,
      onCancelTabClose: cancelPendingTabClose,
      onCheckTabForExternalChange: checkTabForExternalChange,
      onCloseFindAndFocusEditor: closeFindAndFocusEditor,
      onClosePreferences: closePreferencesFromKeyboard,
      onCloseSelectedImagePreview: closeSelectedImagePreview,
      onCreateNewFile: createNewFile,
      onFocusAdjacentTab: focusAdjacentTab,
      onFocusEditorSoon: focusEditorSoon,
      onNeedsWindowCloseConfirmation: requestAppCloseConfirmation,
      onOpenFile: openFile,
      onOpenWorkspace: openWorkspace,
      onRequestCloseTab: requestCloseTab,
      onRequestWindowClose: requestWindowClose,
      onSaveActiveTab: saveActiveTab,
      onSaveActiveTabAs: saveActiveTabAs,
      pendingAppClose,
      pendingCloseTabOpen,
      preferencesCloseButtonRef,
      preferencesDialogRef,
      preferencesOpen,
      selectedImageOpen,
      setEditorSettings,
      setFindVisible,
      setPreferencesDialogMode,
      setPreviewVisible,
      setStatus,
      setZenMode,
      zenMode,
    },
  });

  const shellProps: AppShellProps = {
    activeAgentSession,
    activeConflict,
    activeContents,
    activeDirty,
    activeDocumentLineCount,
    activeDraft,
    activeError,
    activeMatchIndex,
    activeSaveError,
    activeTab,
    activeTabId,
    agentAvailable: agentWorkbenchAvailable,
    agentLaunchGate,
    agentOutput,
    agentSession,
    agentStopPending,
    agentWorkbenchActive,
    agentWorkbenchConsent,
    agentWorkbenchCopy,
    agentWorkbenchPreference,
    agentWorkbenchProvider,
    agentWorkbenchRestartRequired,
    agentModeBadge: agentWorkbenchModeBadge,
    agentModeBadgePending: agentWorkbenchRestartRequired,
    agentModeBadgeTitle: agentWorkbenchCopy.modeBadgeTitle,
    appCloseCancelButtonRef,
    appCloseDialogRef,
    appRestartPending,
    cancelPendingAppClose,
    cancelPendingTabClose,
    clearCompareSource,
    clearCompareTarget,
    clearSaveError,
    closeCompareView,
    closeFindAndFocusEditor,
    closePreferencesFromKeyboard,
    closeQuickOpen,
    closeTabCancelButtonRef,
    closeTabDialogRef,
    closeTabNow,
    closeWorkspaceContextMenu,
    compareAnchor,
    compareTarget,
    compareView,
    compareWorkspaceFiles,
    copyWorkspaceFullPath,
    createNewFile,
    currentHeadingLine: currentMarkdownHeading?.line ?? null,
    detail: activeStatusDetail,
    dirtyTabCount,
    discardAllAndCloseWindow,
    discardDraft,
    documentHeadings,
    documentKey,
    draggingTabId,
    dragOverTabId,
    editorChromeCopy,
    editorPaneRef,
    editorPreviewGridRef,
    editorPreviewGridStyle,
    editorSettings,
    editorTheme,
    emptyTabsLabel: safeEditorCopy.emptyTabs,
    findInputRef,
    findMatchCount,
    findMatches,
    findQuery,
    findVisible,
    getCompareCaseByKey,
    goToLine,
    goToLineValue,
    handleEditorChange,
    handleFindKeyDown,
    handleGoToLineKeyDown,
    handlePasteImage,
    handlePresetPrompt,
    handlePreviewResizeKeyDown,
    handlePreviewResizePointerDown,
    handlePreviewResizePointerMove,
    handleReplaceKeyDown,
    handleSendSelectionToAgent,
    hasWorkspaceSelection,
    invalidRegex,
    jumpToHeading,
    keepEditingAfterConflict,
    loadWorkspaceDirectory,
    menuLanguage,
    onApplyMarkdownFormat: applyActiveMarkdownFormat,
    onCheckAgentGate: requestAgentLaunchGateCheck,
    onCloseTab: requestCloseTab,
    onConvertLineEnding: convertActiveLineEnding,
    onFinishTabPointerDrag: finishTabPointerDrag,
    onInsertTable: insertTable,
    onPointerEnter: suspendAgentUiRefresh,
    onResizeAgentTerminal: resizeAgentTerminal,
    onResumeAgentUiRefresh: resumeAgentUiRefresh,
    onReviewChanges: requestReviewTabAgainstDisk,
    onSelectTab: selectTabFromBar,
    onSendAgentTerminalData: sendAgentTerminalData,
    onStopAgentSession: requestAgentSessionStop,
    onSuspendAgentUiRefresh: suspendAgentUiRefresh,
    onTabPointerDown: handleTabPointerDown,
    onTabPointerMove: handleTabPointerMove,
    onToggleAgent: toggleAgentPane,
    onToggleDiff: toggleDiffPane,
    onToggleOutline: toggleOutlinePane,
    onTogglePreview: togglePreviewPane,
    openFile,
    openFilePath,
    openPreviewMarkdownLink,
    openWorkspace,
    openWorkspaceContextMenu,
    openWorkspaceFile,
    outlineTruncated: documentOutline?.truncated ?? false,
    pendingAppClose,
    pendingCloseTab,
    preferencesCloseButtonRef,
    preferencesCopy,
    preferencesDialogMode,
    preferencesDialogRef,
    preferencesOpen,
    previewColumnPercent,
    previewPaneRef,
    previewVisible,
    quickOpenVisible,
    recentFiles,
    recoveryCopy,
    reopenTabFromDisk,
    replaceAll,
    replaceOne,
    replaceQuery,
    resolvedTheme,
    restartAppForAgentMode,
    reviewDraftAgainstDisk: requestReviewDraftAgainstDisk,
    reviewSurface,
    reviewTabAgainstDisk: requestReviewTabAgainstDisk,
    restoreDraft,
    revealWorkspacePath,
    runSelectedFileCompare,
    safeEditorCopy,
    saveAllAndCloseWindow,
    saveAndClosePendingTab,
    saveTabById,
    scrollHudContext,
    scrollHudLine,
    scrollHudVisible,
    searchOptions,
    selectWorkspaceCompareFile,
    selectedImage,
    sendWorkspacePathToAgent,
    setAgentWorkbenchConsent: updateAgentWorkbenchConsent,
    setAgentWorkbenchPreference: updateAgentWorkbenchPreference,
    setAgentWorkbenchProvider: updateAgentWorkbenchProvider,
    setCompareSource,
    setCompareTargetFile,
    setEditorSettings,
    setFindQuery,
    setGoToLineValue,
    setMenuLanguage,
    setPreviewVisible,
    setReplaceQuery,
    setSearchOptions,
    setSelectionInfo,
    setThemePreference,
    shouldSuppressTabClick,
    showNextMatch,
    showPreviousMatch,
    sidePaneCopy,
    sidePaneMode,
    sidePaneVisible,
    status,
    syncEditorScroll,
    syncPreviewScroll,
    tabs,
    themePreference,
    workspaceContextMenu,
    workspaceRootPath,
    workspaceTree,
    zenMode,
  };

  return <AppShell {...shellProps} />;
}
